version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
